version: '3.5' 

services:
  back:
    image: backend
    ports: 
      - 8000:8000
    environment: 
      - REDIS_HOST=redis
    
  front:
    image: frontend
    ports: 
      - 5000:5000

  redis:
    image: redis