version: '3.5'

services:
  back:
    image: backend
    ports: 
      - 8000:8000
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    
  front:
    image: frontend
    ports: 
      - 5000:5000

  redis:
    image: redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres