version: '3.5'

services:
  back:
    ports: 
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - PORT=8000
    image: backend
    networks:
      - ntwrk 
    restart: unless-stopped
    depends_on:
      - postgres

  front:
    image: frontend
    ports: 
      - 5000:5000
    networks:
      - ntwrk

  redis:
    image: redis
    volumes:
      - data:/etc/data
    networks:
      - ntwrk

  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres
    networks:
      - ntwrk
  
  server:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - back
    networks:
      - ntwrk

volumes:
  data:

networks:
  ntwrk:
    name: ntwrk
